version: '3.8'
services:
  bjbot:
    build: ./
    container_name: bot-service
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - bot_db
    environment:
      - BOT_NAME=${BJBOT_NAME}
      - BOT_KEY=${BJBOT_KEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bot_db:5432/bj-bot
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  bot_db:
      image: postgres:15.1-alpine
      container_name: bot_db
      restart: on-failure
      ports:
        - "6543:5432"
      volumes:
        - bot_db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=bj-bot
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
volumes:
  bot_db: